### ISSUE TITLE
Index.php missing

### ISSUE THREAD

**Issue by aaryadev** [YashKumarVerma/General-Purpose-PHP-Framework#1]
As all request pass through index.php due to rewriterule from htaccess.
Seems like codeigniter base clone

**Comment by YashKumarVerma** [comment]
Not at all a clone. For all the scripts which pass requests through index.php are not clones. It's just a method of use. 
P.S. => use the package included.

**Comment by aaryadev** [comment]
Please extract package and update index.php else whoever  try to use it they will find index.php missing

**Comment by YashKumarVerma** [comment]
Added 8 minutes ago and you are commenting 4 minutes ago of this post. 
Kindly refer the repo before posting.
Thanks

**Comment by aaryadev** [comment]
the repo took 11 minute to update..

**Comment by YashKumarVerma** [comment]
that's the time with reference from the time that comment was written

**Comment by aaryadev** [comment]
you had messup in files as you said in FB.
have great coding..

**Comment by YashKumarVerma** [comment]
i'm new to git but not php

**Comment by YashKumarVerma** [comment]
changing the name of repo caused the problem

**Comment by YashKumarVerma** [comment]
By the way, thanks for showing concern.
