### ISSUE TITLE
week security.

### ISSUE THREAD

**Issue by aaryadev** [YashKumarVerma/General-Purpose-PHP-Framework#2]
In application/processor/vital_functions.php
password has only md5 which is considered to be very weak hashing .
Please also use sha1/salting..

**Comment by YashKumarVerma** [comment]
Kindly notice, that function is made only for demonstration and is therefore placed in a separate file. This allows the programmer to allow custom made encryption easily. 

NOT A SECURITY ISSUE BUT FEATURE
