### ISSUE TITLE
API key.

### ISSUE THREAD

**Issue by Maikuolan** [YashKumarVerma/General-Purpose-PHP-Framework#6]
([config.php:L30](https://github.com/YashKumarVerma/General-Purpose-PHP-Framework/blob/master/application/processor/config.php#L30))
```
$protected['map_api']['key']	= "bfbecb61818c225378eaa662b537e570";
```

If that's an actual real API key of yours, you probably don't want to be exposing this. Better to leave this variable empty and just describe what users are meant to put there.

**Comment by YashKumarVerma** [comment]
Thanks for showing your concern. 
But the `key` which you see there is actually the `hash` of this string `your_api_key`

**Comment by YashKumarVerma** [comment]
I suppose this issue is solved . 
(it's actually the `md5` of `your_api_key` )

**Comment by Maikuolan** [comment]
Yep. :-)

This issue was created due to the concern that it might've been a personal API key of yours. If it's not, then, the issue can be safely closed.

**Comment by YashKumarVerma** [comment]
Thanks for showing your concern.
